### ISSUE TITLE
cannot signup - says "Error processing form."

### ISSUE THREAD

**Issue by yejipark** [WeStudee/WeStudee#57]
![image](https://cloud.githubusercontent.com/assets/11168182/7099635/b8edca12-dfc5-11e4-9baf-54690228e733.png)

Using chrome on my laptop. I tried making a new account (both using gmail and wesleyan email) but it didn't work. (Pi experienced the same problem.) Also the description 'Error processing form' can be more specific. For example: "Error with email address: use your school email."  "Error with password setting: make sure to use a combination of numbers and capital letters."

**Comment by yutarochan** [comment]
Press F12 and open up the "Chrome Developer Tools" and click the "Console" Tab.
You should see some red text there that indicates an error. Please copy and paste the output as this would really help me narrow down what's causing the bug.

**Comment by yejipark** [comment]
Hi Yuya, I followed your instruction and clicked the Console Tab but no red text appeared. 
![image](https://cloud.githubusercontent.com/assets/11168182/7107107/3a7e7056-e127-11e4-922f-0bd96f204722.png)

**Comment by pi-paticha** [comment]
This came up when I'm trying to register for an account in chrome

POST https://api.parse.com/1/login 404 (Not Found) parse-1.3.3.min.js:1

**Comment by yutarochan** [comment]
Fixed: Issue seemed to be due to a the gender values not going through properly.
Please try creating an account again and see if it works.

**Comment by pi-paticha** [comment]
Hi, I tried signing up again and still doesn't work: 
5 Failed to load resource: the server responded with a status of 404 (Not Found) https://api.parse.com/1/login
